/*
 * GENERATED FILE - DO NOT EDIT.
 *
 * Produced by tools/so2h_gen_scene.py from tools/scenes/pause.py, which is the single
 * source of truth for this layout. Editing this file by hand will be undone by the next
 * run of the generator, and CI runs it with --check.
 *
 * Edit the scene, then: python3 tools/so2h_gen_scene.py
 */

#ifndef SO2H_UI_SCENE_PAUSE_H
#define SO2H_UI_SCENE_PAUSE_H

#include "so2h_ui.h"

// One identifier per authored node. Content code addresses the menu through these and
// never through a raw index, so inserting a window in pause.py cannot silently renumber
// something a draw callback was pointing at.
typedef enum So2hUiPauseId {
    SO2H_PAUSE_ROOT,
    SO2H_PAUSE_RIGHT_WALL,
    SO2H_PAUSE_BOTTOM_WALL,
    SO2H_PAUSE_GAME_SCREEN,
    SO2H_PAUSE_GAME_DECO,
    SO2H_PAUSE_PEEP_LEFT,
    SO2H_PAUSE_PEEP_RIGHT,
    SO2H_PAUSE_QUEST_WIN,
    SO2H_PAUSE_LEFT_WIN,
    SO2H_PAUSE_REMAINS_WIN,
    SO2H_PAUSE_HEART_WIN,
    SO2H_PAUSE_ITEM_ROW,
    SO2H_PAUSE_QUEST_SLOT00,
    SO2H_PAUSE_QUEST_SLOT01,
    SO2H_PAUSE_QUEST_SLOT02,
    SO2H_PAUSE_QUEST_SLOT10,
    SO2H_PAUSE_QUEST_SLOT11,
    SO2H_PAUSE_QUEST_SLOT12,
    SO2H_PAUSE_NOTEBOOK,
    SO2H_PAUSE_STAT_WIN,
    SO2H_PAUSE_STAT_L,
    SO2H_PAUSE_STAT_M,
    SO2H_PAUSE_STAT_R,
    SO2H_PAUSE_STAT_LUP,
    SO2H_PAUSE_STAT_LDOWN,
    SO2H_PAUSE_STAT_MUP,
    SO2H_PAUSE_STAT_MDOWN,
    SO2H_PAUSE_STAT_RUP,
    SO2H_PAUSE_STAT_RDOWN,
    SO2H_PAUSE_STAT_LROW0,
    SO2H_PAUSE_STAT_LROW1,
    SO2H_PAUSE_STAT_LROW2,
    SO2H_PAUSE_STAT_LROW3,
    SO2H_PAUSE_STAT_LROW4,
    SO2H_PAUSE_STAT_LROW5,
    SO2H_PAUSE_STAT_LROW6,
    SO2H_PAUSE_STAT_LROW7,
    SO2H_PAUSE_STAT_LROW8,
    SO2H_PAUSE_STAT_MROW0,
    SO2H_PAUSE_STAT_MROW1,
    SO2H_PAUSE_STAT_MROW2,
    SO2H_PAUSE_STAT_MROW3,
    SO2H_PAUSE_STAT_MROW4,
    SO2H_PAUSE_STAT_MROW5,
    SO2H_PAUSE_STAT_MROW6,
    SO2H_PAUSE_STAT_MROW7,
    SO2H_PAUSE_STAT_MROW8,
    SO2H_PAUSE_STAT_RROW0,
    SO2H_PAUSE_STAT_RROW1,
    SO2H_PAUSE_STAT_RROW2,
    SO2H_PAUSE_STAT_RROW3,
    SO2H_PAUSE_STAT_RROW4,
    SO2H_PAUSE_STAT_RROW5,
    SO2H_PAUSE_STAT_RROW6,
    SO2H_PAUSE_STAT_RROW7,
    SO2H_PAUSE_STAT_RROW8,
    SO2H_PAUSE_BONUS_WIN,
    SO2H_PAUSE_SONG_PREV_WIN,
    SO2H_PAUSE_SONG_STAFF,
    SO2H_PAUSE_SONG_SEL_WIN,
    SO2H_PAUSE_SONG_NOTES,
    SO2H_PAUSE_SONG_PAGE_L,
    SO2H_PAUSE_SONG_PAGE_R,
    SO2H_PAUSE_SONG00,
    SO2H_PAUSE_SONG01,
    SO2H_PAUSE_SONG02,
    SO2H_PAUSE_SONG03,
    SO2H_PAUSE_SONG04,
    SO2H_PAUSE_SONG05,
    SO2H_PAUSE_SONG10,
    SO2H_PAUSE_SONG11,
    SO2H_PAUSE_SONG12,
    SO2H_PAUSE_SONG13,
    SO2H_PAUSE_SONG14,
    SO2H_PAUSE_SONG15,
    SO2H_PAUSE_CTX_WIN,
    SO2H_PAUSE_CTX_ROW0,
    SO2H_PAUSE_CTX_ROW1,
    SO2H_PAUSE_CTX_ROW2,
    SO2H_PAUSE_PAGE_LEFT,
    SO2H_PAUSE_PAGE_RIGHT,
    SO2H_PAUSE_TOOL00,
    SO2H_PAUSE_TOOL01,
    SO2H_PAUSE_TOOL02,
    SO2H_PAUSE_TOOL03,
    SO2H_PAUSE_TOOL04,
    SO2H_PAUSE_TOOL05,
    SO2H_PAUSE_TOOL06,
    SO2H_PAUSE_TOOL07,
    SO2H_PAUSE_TOOL08,
    SO2H_PAUSE_TOOL09,
    SO2H_PAUSE_TOOL10,
    SO2H_PAUSE_TOOL11,
    SO2H_PAUSE_TOOL12,
    SO2H_PAUSE_TOOL13,
    SO2H_PAUSE_TOOL14,
    SO2H_PAUSE_TOOL15,
    SO2H_PAUSE_TOOL16,
    SO2H_PAUSE_TOOL17,
    SO2H_PAUSE_TOOL18,
    SO2H_PAUSE_TOOL19,
    SO2H_PAUSE_TOOL20,
    SO2H_PAUSE_TOOL21,
    SO2H_PAUSE_TOOL22,
    SO2H_PAUSE_TOOL23,
    SO2H_PAUSE_TOOL24,
    SO2H_PAUSE_TOOL25,
    SO2H_PAUSE_NODE_MAX
} So2hUiPauseId;

// The generated table. Pass straight to So2h_Ui_Init.
const So2hUiDesc* So2h_UiScene_Pause(s32* outCount);
const So2hUiVariant* So2h_UiScene_PauseVariants(s32* outCount);

#endif
