// GENERATED by tools/so2h_gen_sheets.py from
// mm/assets/custom/textures/so2h_menu/sheets.json - do not edit by hand.

#include "so2h_ui_sheets.h"
#include "assets/2s2h_assets.h"
#include "assets/so2h_ui_sheets_assets.h"

const So2hUiSheetDef gSo2hUiSheets[SO2H_SHEET_MAX] = {
    // Contentless-filled. The only textbook nine-slice of the five: tile map A B B C D / E F F F G / H F F F I / J F F F K / L M N N O, single self-tiling opaque interior F. Primary body panel.
    [SO2H_SHEET_SHEETFRAMEFILLED] = { SO2H_SHEET_SHEETFRAMEFILLED, gSo2hSheetFrameFilledTex, 320, 320, 64, 5, 5, SO2H_UI_FMT_RGBA32, 2, 2, 2, 2, 0, 64, 64, 64, 64, 128, 128, 128, 128, SO2H_UI_GROW_RUN, "gSo2hSheetFrameFilled" },
    // Empty_Frame. Its centre cell is fully transparent ON PURPOSE - this is the frame you put over live content - so hollowInterior waives the generator's transparent-run-cell check. Hand-packed with cross-row reuse (A B B C D / E F G H I / J K L J K / M N B O P / Q R G G S). Interior is decorated, not flat, so it grows well horizontally and is best kept near native height.
    [SO2H_SHEET_SHEETFRAMEEMPTY] = { SO2H_SHEET_SHEETFRAMEEMPTY, gSo2hSheetFrameEmptyTex, 320, 320, 64, 5, 5, SO2H_UI_FMT_RGBA32, 2, 2, 2, 2, 0, 64, 64, 64, 64, 128, 128, 128, 128, SO2H_UI_GROW_RUN, "gSo2hSheetFrameEmpty" },
    // Raising_Window. 23 of 25 cells unique; top row A B B C D.
    [SO2H_SHEET_SHEETFRAMERAISING] = { SO2H_SHEET_SHEETFRAMERAISING, gSo2hSheetFrameRaisingTex, 320, 320, 64, 5, 5, SO2H_UI_FMT_RGBA32, 2, 2, 2, 2, 0, 64, 64, 64, 64, 128, 128, 128, 128, SO2H_UI_GROW_RUN, "gSo2hSheetFrameRaising" },
    // Backed_Frame. Same tile-identity map as Raising.
    [SO2H_SHEET_SHEETFRAMEBACKED] = { SO2H_SHEET_SHEETFRAMEBACKED, gSo2hSheetFrameBackedTex, 320, 320, 64, 5, 5, SO2H_UI_FMT_RGBA32, 2, 2, 2, 2, 0, 64, 64, 64, 64, 128, 128, 128, 128, SO2H_UI_GROW_RUN, "gSo2hSheetFrameBacked" },
    // Replacement-technicalUI_Popup. Genuinely a different frame, not a shifted copy: A B C C D / E F G H I / J K L M N / O P Q R S / T U U V W.
    [SO2H_SHEET_SHEETFRAMEPOPUP] = { SO2H_SHEET_SHEETFRAMEPOPUP, gSo2hSheetFramePopupTex, 320, 320, 64, 5, 5, SO2H_UI_FMT_RGBA32, 2, 2, 2, 2, 0, 64, 64, 64, 64, 128, 128, 128, 128, SO2H_UI_GROW_RUN, "gSo2hSheetFramePopup" },
    // Base-Semi-Transparent_Window. Interior is a flat alpha-176 wash, so this is the default backing for ANY window drawn OVER live content - overlays, popups, page panels. Same tile-identity map as Raising/Backed (A B B C D / E F G H I / J K L M N / O P Q R S / T U V V W), 23 of 25 unique, single middle run cell on both axes.
    [SO2H_SHEET_SHEETFRAMEGLASS] = { SO2H_SHEET_SHEETFRAMEGLASS, gSo2hSheetFrameGlassTex, 320, 320, 64, 5, 5, SO2H_UI_FMT_RGBA32, 2, 2, 2, 2, 0, 64, 64, 64, 64, 128, 128, 128, 128, SO2H_UI_GROW_RUN, "gSo2hSheetFrameGlass" },
    // Horizontal extendable strip. Rows 0 and 3 are fully transparent padding; rows 1-2 are cap + repeating middle + cap (B C C C C C C D / E F G G G G G H). No vertical run band - it was not drawn to grow downward.
    [SO2H_SHEET_SHEETSONGBACKDROP] = { SO2H_SHEET_SHEETSONGBACKDROP, gSo2hSheetSongBackdropTex, 256, 128, 32, 8, 4, SO2H_UI_FMT_RGBA32, 2, 2, 0, 255, 0, 32, 32, 32, 32, 32, 32, 32, 32, SO2H_UI_GROW_RUN, "gSo2hSheetSongBackdrop" },
    // Atlas, 9 unique corner patches for where two panels meet. No repeated tiles.
    [SO2H_SHEET_SHEETCORNERFIX] = { SO2H_SHEET_SHEETCORNERFIX, gSo2hSheetCornerFixTex, 192, 192, 64, 3, 3, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 64, 64, 64, 64, 64, 64, 64, 64, SO2H_UI_GROW_RUN, "gSo2hSheetCornerFix" },
    // Atlas of 4 INDIVIDUAL button sprites - NOT a frame. Never nine-slice or tile this sheet; draw one slice at native size. Top row is the round pill (normal / red), bottom row is the square container (raised / sunken).
    [SO2H_SHEET_SHEETBIGBUTTON] = { SO2H_SHEET_SHEETBIGBUTTON, gSo2hSheetBigButtonTex, 128, 128, 64, 2, 2, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hSheetBigButton" },
    // Atlas, 16 content-container pieces. No repeated tiles.
    [SO2H_SHEET_SHEETCONTENTBOX] = { SO2H_SHEET_SHEETCONTENTBOX, gSo2hSheetContentBoxTex, 128, 128, 32, 4, 4, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hSheetContentBox" },
    // Atlas, 16 mini-button and textbox pieces. No repeated tiles.
    [SO2H_SHEET_SHEETMINIBUTTON] = { SO2H_SHEET_SHEETMINIBUTTON, gSo2hSheetMiniButtonTex, 128, 128, 32, 4, 4, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hSheetMiniButton" },
    // The item and button icon atlas, 448x480, 167/210 cells unique. Addressed by So2h_Ui_Slice(sheet, col, row). No named slices yet: the sheet carries only 4 of the 6 medallions and no spiritual stones, and the decision was to source ALL medallions from the OoT rips behind a one-line art-source table rather than mix two art origins on one row.
    [SO2H_SHEET_SHEETITEMS] = { SO2H_SHEET_SHEETITEMS, gSo2hSheetItemsTex, 448, 480, 32, 14, 15, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hSheetItems" },
    // Contentless-filled 9-slice, 3x3 @64, all 9 cells unique, opaque self-tiling centre. The true textbook nine-slice of the set - one border ring, one repeating middle. Use where a small opaque slab is wanted without FrameFilled's two-ring bulk.
    [SO2H_SHEET_SHEETSLAB9] = { SO2H_SHEET_SHEETSLAB9, gSo2hSheetSlab9Tex, 192, 192, 64, 3, 3, SO2H_UI_FMT_RGBA32, 1, 1, 1, 1, 0, 64, 64, 64, 64, 64, 64, 64, 64, SO2H_UI_GROW_RUN, "gSo2hSheetSlab9" },
    // FullBorder-EmptyContent, 3x3 @64. Deep bevelled border with a FULLY TRANSPARENT centre - the frame you put over live content or a sprite. hollowInterior waives the transparent-run-cell check.
    [SO2H_SHEET_SHEETSLOTEMPTY] = { SO2H_SHEET_SHEETSLOTEMPTY, gSo2hSheetSlotEmptyTex, 192, 192, 64, 3, 3, SO2H_UI_FMT_RGBA32, 1, 1, 1, 1, 0, 64, 64, 64, 64, 64, 64, 64, 64, SO2H_UI_GROW_RUN, "gSo2hSheetSlotEmpty" },
    // FullBorder-ItemContainer, 3x3 @64. Same bevelled border as SlotEmpty but with an INSET dark recessed interior. This is the item-slot look: the quest/equip grid squares are this, not BigButton. BigButton SQUARE is the OUTSET/raised variant, used for the one slot that is meant to pop (the Bombers' Notebook).
    [SO2H_SHEET_SHEETSLOTITEM] = { SO2H_SHEET_SHEETSLOTITEM, gSo2hSheetSlotItemTex, 192, 192, 64, 3, 3, SO2H_UI_FMT_RGBA32, 1, 1, 1, 1, 0, 64, 64, 64, 64, 64, 64, 64, 64, SO2H_UI_GROW_RUN, "gSo2hSheetSlotItem" },
    // FullThin-Border container, 3x3 @64. Narrow bevel, transparent centre. For readouts and counters where a full border would eat the content area.
    [SO2H_SHEET_SHEETSLOTTHIN] = { SO2H_SHEET_SHEETSLOTTHIN, gSo2hSheetSlotThinTex, 192, 192, 64, 3, 3, SO2H_UI_FMT_RGBA32, 1, 1, 1, 1, 0, 64, 64, 64, 64, 64, 64, 64, 64, SO2H_UI_GROW_RUN, "gSo2hSheetSlotThin" },
    // FullBorder-ItemContainer at 5x5 @64 - the grow-friendly version of SlotItem. Interior is a single repeated tile G across the whole 3x3 middle (A B C D E / F G G G H / I G G G H / J G G G H / K L M N O), so it tiles cleanly to any size. Use for a recessed panel that has to grow; use SlotItem for a single native-ish slot.
    [SO2H_SHEET_SHEETITEMBOX] = { SO2H_SHEET_SHEETITEMBOX, gSo2hSheetItemBoxTex, 320, 320, 64, 5, 5, SO2H_UI_FMT_RGBA32, 2, 2, 2, 2, 0, 64, 64, 64, 64, 128, 128, 128, 128, SO2H_UI_GROW_RUN, "gSo2hSheetItemBox" },
    [SO2H_SHEET_BTNA] = { SO2H_SHEET_BTNA, gSo2hBtnATex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hBtnA" },
    [SO2H_SHEET_BTNARROWDOWN] = { SO2H_SHEET_BTNARROWDOWN, gSo2hBtnArrowDownTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hBtnArrowDown" },
    [SO2H_SHEET_BTNARROWLEFT] = { SO2H_SHEET_BTNARROWLEFT, gSo2hBtnArrowLeftTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hBtnArrowLeft" },
    [SO2H_SHEET_BTNARROWRIGHT] = { SO2H_SHEET_BTNARROWRIGHT, gSo2hBtnArrowRightTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hBtnArrowRight" },
    [SO2H_SHEET_BTNARROWUP] = { SO2H_SHEET_BTNARROWUP, gSo2hBtnArrowUpTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hBtnArrowUp" },
    [SO2H_SHEET_BTNB] = { SO2H_SHEET_BTNB, gSo2hBtnBTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hBtnB" },
    [SO2H_SHEET_BTNCDOWN] = { SO2H_SHEET_BTNCDOWN, gSo2hBtnCDownTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hBtnCDown" },
    [SO2H_SHEET_BTNCLEFT] = { SO2H_SHEET_BTNCLEFT, gSo2hBtnCLeftTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hBtnCLeft" },
    [SO2H_SHEET_BTNCRIGHT] = { SO2H_SHEET_BTNCRIGHT, gSo2hBtnCRightTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hBtnCRight" },
    [SO2H_SHEET_BTNCUP] = { SO2H_SHEET_BTNCUP, gSo2hBtnCUpTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hBtnCUp" },
    [SO2H_SHEET_BTNCIRCLE] = { SO2H_SHEET_BTNCIRCLE, gSo2hBtnCircleTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hBtnCircle" },
    [SO2H_SHEET_BTNCROSS] = { SO2H_SHEET_BTNCROSS, gSo2hBtnCrossTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hBtnCross" },
    [SO2H_SHEET_CELLTILE] = { SO2H_SHEET_CELLTILE, gSo2hCellTileTex, 70, 70, 70, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hCellTile" },
    [SO2H_SHEET_CROSSRED] = { SO2H_SHEET_CROSSRED, gSo2hCrossRedTex, 70, 70, 70, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hCrossRed" },
    [SO2H_SHEET_FRAMEBL] = { SO2H_SHEET_FRAMEBL, gSo2hFrameBLTex, 52, 52, 52, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hFrameBL" },
    [SO2H_SHEET_FRAMEBR] = { SO2H_SHEET_FRAMEBR, gSo2hFrameBRTex, 52, 52, 52, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hFrameBR" },
    [SO2H_SHEET_FRAMEBOTTOM] = { SO2H_SHEET_FRAMEBOTTOM, gSo2hFrameBottomTex, 35, 52, 52, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hFrameBottom" },
    [SO2H_SHEET_FRAMEFILL] = { SO2H_SHEET_FRAMEFILL, gSo2hFrameFillTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hFrameFill" },
    [SO2H_SHEET_FRAMELEFT] = { SO2H_SHEET_FRAMELEFT, gSo2hFrameLeftTex, 52, 35, 52, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hFrameLeft" },
    [SO2H_SHEET_FRAMERIGHT] = { SO2H_SHEET_FRAMERIGHT, gSo2hFrameRightTex, 52, 35, 52, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hFrameRight" },
    [SO2H_SHEET_FRAMETL] = { SO2H_SHEET_FRAMETL, gSo2hFrameTLTex, 52, 52, 52, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hFrameTL" },
    [SO2H_SHEET_FRAMETR] = { SO2H_SHEET_FRAMETR, gSo2hFrameTRTex, 52, 52, 52, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hFrameTR" },
    [SO2H_SHEET_FRAMETOP] = { SO2H_SHEET_FRAMETOP, gSo2hFrameTopTex, 35, 52, 52, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hFrameTop" },
    [SO2H_SHEET_MARKPAWNCYAN] = { SO2H_SHEET_MARKPAWNCYAN, gSo2hMarkPawnCyanTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hMarkPawnCyan" },
    [SO2H_SHEET_MARKPAWNCYANX] = { SO2H_SHEET_MARKPAWNCYANX, gSo2hMarkPawnCyanXTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hMarkPawnCyanX" },
    [SO2H_SHEET_MARKPAWNDARK] = { SO2H_SHEET_MARKPAWNDARK, gSo2hMarkPawnDarkTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hMarkPawnDark" },
    [SO2H_SHEET_MARKPAWNLIGHT] = { SO2H_SHEET_MARKPAWNLIGHT, gSo2hMarkPawnLightTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hMarkPawnLight" },
    [SO2H_SHEET_MARKT] = { SO2H_SHEET_MARKT, gSo2hMarkTTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hMarkT" },
    [SO2H_SHEET_MARKTRIDARK] = { SO2H_SHEET_MARKTRIDARK, gSo2hMarkTriDarkTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hMarkTriDark" },
    [SO2H_SHEET_MARKTRIGOLD] = { SO2H_SHEET_MARKTRIGOLD, gSo2hMarkTriGoldTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hMarkTriGold" },
    [SO2H_SHEET_MARKVS] = { SO2H_SHEET_MARKVS, gSo2hMarkVsTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hMarkVs" },
    [SO2H_SHEET_NOTEBLACK] = { SO2H_SHEET_NOTEBLACK, gSo2hNoteBlackTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hNoteBlack" },
    [SO2H_SHEET_NOTEBLUE] = { SO2H_SHEET_NOTEBLUE, gSo2hNoteBlueTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hNoteBlue" },
    [SO2H_SHEET_NOTELOCKED] = { SO2H_SHEET_NOTELOCKED, gSo2hNoteLockedTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hNoteLocked" },
    [SO2H_SHEET_NOTEWHITE] = { SO2H_SHEET_NOTEWHITE, gSo2hNoteWhiteTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hNoteWhite" },
    [SO2H_SHEET_ROUNDTILE] = { SO2H_SHEET_ROUNDTILE, gSo2hRoundTileTex, 70, 70, 70, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hRoundTile" },
    [SO2H_SHEET_SLOTDARK] = { SO2H_SHEET_SLOTDARK, gSo2hSlotDarkTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hSlotDark" },
    [SO2H_SHEET_SLOTHATCH] = { SO2H_SHEET_SLOTHATCH, gSo2hSlotHatchTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hSlotHatch" },
    [SO2H_SHEET_SLOTLIGHT] = { SO2H_SHEET_SLOTLIGHT, gSo2hSlotLightTex, 35, 35, 35, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hSlotLight" },
    [SO2H_SHEET_SLOTRECESS] = { SO2H_SHEET_SLOTRECESS, gSo2hSlotRecessTex, 70, 70, 70, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hSlotRecess" },
    [SO2H_SHEET_STAFFCLEF] = { SO2H_SHEET_STAFFCLEF, gSo2hStaffClefTex, 35, 70, 70, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hStaffClef" },
    [SO2H_SHEET_STAFFLINES] = { SO2H_SHEET_STAFFLINES, gSo2hStaffLinesTex, 70, 70, 70, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hStaffLines" },
    [SO2H_SHEET_WINDOW] = { SO2H_SHEET_WINDOW, gSo2hWindowTex, 210, 210, 210, 1, 1, SO2H_UI_FMT_RGBA32, 0, 255, 0, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, SO2H_UI_GROW_RUN, "gSo2hWindow" },
};
