#ifndef Z_SCENE_ORIGIN_H
#define Z_SCENE_ORIGIN_H

/**
 * so2h [Scene] patch 0003 - scene-origin (OOT/MM) tagging system.
 *
 * See /home/user/ProjectZ/env/so2h/patches/0003_scene_origin_tagging.md for full design
 * rationale. Summary of the key decision this file implements:
 *
 * OOT's ~110 scenes are deliberately NOT appended into MM's native `SceneId` enum /
 * `gSceneTable[SCENE_MAX]` numeric space, because three real MM structures are sized/
 * typed for MM's own scene count only and would silently overflow or need a save-
 * format change to extend safely (confirmed by direct read this session):
 *   - `SaveInfo.permanentSceneFlags[120]` and `SaveContext.cycleSceneFlags[120]`
 *     (z64save.h) - fixed-size 120-entry arrays; MM's SCENE_MAX is already 113, only
 *     7 slack slots. +110 OOT scenes would overflow persisted save data.
 *   - `EntranceTableEntry.sceneId` (z64scene.h) is `s8` (max 127); MM's SCENE_MAX=113
 *     leaves only 14 slack values.
 *
 * Instead, OOT scenes get their own independent 0-based `SceneIdOot` enum (this file,
 * mechanically generated by tools/gen_scene_origin.py from reference/soh's real scene
 * table - never hand-transcribed, same rationale as STRICTRULES.md rule 20). Any code
 * that needs to refer to "a scene from either game" uses the `CompatSceneRef` tagged
 * union below instead of a single raw int, and any OOT-specific persisted per-scene
 * data (flags, visited state) must get its own appropriately-sized storage under
 * `ShipSaveInfo` (z64save.h) - never packed into MM's own fixed-size arrays.
 *
 * Confirmed collision: `SCENE_LOST_WOODS` exists in both games' native scene tables
 * (fitting, since Lost Woods is the planned world-swap connector location per the
 * OOT-in-MM design). so2h's OOT scene enum values are namespaced `SCENE_OOT_*`
 * throughout to avoid any ambiguity with MM's own `SCENE_LOST_WOODS`.
 */

#include "global.h"

// Mechanically generated by tools/gen_scene_origin.py from
// reference/soh/soh/include/tables/scene_table.h (110 scenes).
// Never hand-edit — regenerate and re-paste instead (STRICTRULES.md rule 20 spirit).
typedef enum SceneIdOot {
    /* 0x00 */ SCENE_OOT_DEKU_TREE,
    /* 0x01 */ SCENE_OOT_DODONGOS_CAVERN,
    /* 0x02 */ SCENE_OOT_JABU_JABU,
    /* 0x03 */ SCENE_OOT_FOREST_TEMPLE,
    /* 0x04 */ SCENE_OOT_FIRE_TEMPLE,
    /* 0x05 */ SCENE_OOT_WATER_TEMPLE,
    /* 0x06 */ SCENE_OOT_SPIRIT_TEMPLE,
    /* 0x07 */ SCENE_OOT_SHADOW_TEMPLE,
    /* 0x08 */ SCENE_OOT_BOTTOM_OF_THE_WELL,
    /* 0x09 */ SCENE_OOT_ICE_CAVERN,
    /* 0x0A */ SCENE_OOT_GANONS_TOWER,
    /* 0x0B */ SCENE_OOT_GERUDO_TRAINING_GROUND,
    /* 0x0C */ SCENE_OOT_THIEVES_HIDEOUT,
    /* 0x0D */ SCENE_OOT_INSIDE_GANONS_CASTLE,
    /* 0x0E */ SCENE_OOT_GANONS_TOWER_COLLAPSE_INTERIOR,
    /* 0x0F */ SCENE_OOT_INSIDE_GANONS_CASTLE_COLLAPSE,
    /* 0x10 */ SCENE_OOT_TREASURE_BOX_SHOP,
    /* 0x11 */ SCENE_OOT_DEKU_TREE_BOSS,
    /* 0x12 */ SCENE_OOT_DODONGOS_CAVERN_BOSS,
    /* 0x13 */ SCENE_OOT_JABU_JABU_BOSS,
    /* 0x14 */ SCENE_OOT_FOREST_TEMPLE_BOSS,
    /* 0x15 */ SCENE_OOT_FIRE_TEMPLE_BOSS,
    /* 0x16 */ SCENE_OOT_WATER_TEMPLE_BOSS,
    /* 0x17 */ SCENE_OOT_SPIRIT_TEMPLE_BOSS,
    /* 0x18 */ SCENE_OOT_SHADOW_TEMPLE_BOSS,
    /* 0x19 */ SCENE_OOT_GANONDORF_BOSS,
    /* 0x1A */ SCENE_OOT_GANONS_TOWER_COLLAPSE_EXTERIOR,
    /* 0x1B */ SCENE_OOT_MARKET_ENTRANCE_DAY,
    /* 0x1C */ SCENE_OOT_MARKET_ENTRANCE_NIGHT,
    /* 0x1D */ SCENE_OOT_MARKET_ENTRANCE_RUINS,
    /* 0x1E */ SCENE_OOT_BACK_ALLEY_DAY,
    /* 0x1F */ SCENE_OOT_BACK_ALLEY_NIGHT,
    /* 0x20 */ SCENE_OOT_MARKET_DAY,
    /* 0x21 */ SCENE_OOT_MARKET_NIGHT,
    /* 0x22 */ SCENE_OOT_MARKET_RUINS,
    /* 0x23 */ SCENE_OOT_TEMPLE_OF_TIME_EXTERIOR_DAY,
    /* 0x24 */ SCENE_OOT_TEMPLE_OF_TIME_EXTERIOR_NIGHT,
    /* 0x25 */ SCENE_OOT_TEMPLE_OF_TIME_EXTERIOR_RUINS,
    /* 0x26 */ SCENE_OOT_KNOW_IT_ALL_BROS_HOUSE,
    /* 0x27 */ SCENE_OOT_TWINS_HOUSE,
    /* 0x28 */ SCENE_OOT_MIDOS_HOUSE,
    /* 0x29 */ SCENE_OOT_SARIAS_HOUSE,
    /* 0x2A */ SCENE_OOT_KAKARIKO_CENTER_GUEST_HOUSE,
    /* 0x2B */ SCENE_OOT_BACK_ALLEY_HOUSE,
    /* 0x2C */ SCENE_OOT_BAZAAR,
    /* 0x2D */ SCENE_OOT_KOKIRI_SHOP,
    /* 0x2E */ SCENE_OOT_GORON_SHOP,
    /* 0x2F */ SCENE_OOT_ZORA_SHOP,
    /* 0x30 */ SCENE_OOT_POTION_SHOP_KAKARIKO,
    /* 0x31 */ SCENE_OOT_POTION_SHOP_MARKET,
    /* 0x32 */ SCENE_OOT_BOMBCHU_SHOP,
    /* 0x33 */ SCENE_OOT_HAPPY_MASK_SHOP,
    /* 0x34 */ SCENE_OOT_LINKS_HOUSE,
    /* 0x35 */ SCENE_OOT_DOG_LADY_HOUSE,
    /* 0x36 */ SCENE_OOT_STABLE,
    /* 0x37 */ SCENE_OOT_IMPAS_HOUSE,
    /* 0x38 */ SCENE_OOT_LAKESIDE_LABORATORY,
    /* 0x39 */ SCENE_OOT_CARPENTERS_TENT,
    /* 0x3A */ SCENE_OOT_GRAVEKEEPERS_HUT,
    /* 0x3B */ SCENE_OOT_GREAT_FAIRYS_FOUNTAIN_MAGIC,
    /* 0x3C */ SCENE_OOT_FAIRYS_FOUNTAIN,
    /* 0x3D */ SCENE_OOT_GREAT_FAIRYS_FOUNTAIN_SPELLS,
    /* 0x3E */ SCENE_OOT_GROTTOS,
    /* 0x3F */ SCENE_OOT_REDEAD_GRAVE,
    /* 0x40 */ SCENE_OOT_GRAVE_WITH_FAIRYS_FOUNTAIN,
    /* 0x41 */ SCENE_OOT_ROYAL_FAMILYS_TOMB,
    /* 0x42 */ SCENE_OOT_SHOOTING_GALLERY,
    /* 0x43 */ SCENE_OOT_TEMPLE_OF_TIME,
    /* 0x44 */ SCENE_OOT_CHAMBER_OF_THE_SAGES,
    /* 0x45 */ SCENE_OOT_CASTLE_COURTYARD_GUARDS_DAY,
    /* 0x46 */ SCENE_OOT_CASTLE_COURTYARD_GUARDS_NIGHT,
    /* 0x47 */ SCENE_OOT_CUTSCENE_MAP,
    /* 0x48 */ SCENE_OOT_WINDMILL_AND_DAMPES_GRAVE,
    /* 0x49 */ SCENE_OOT_FISHING_POND,
    /* 0x4A */ SCENE_OOT_CASTLE_COURTYARD_ZELDA,
    /* 0x4B */ SCENE_OOT_BOMBCHU_BOWLING_ALLEY,
    /* 0x4C */ SCENE_OOT_LON_LON_BUILDINGS,
    /* 0x4D */ SCENE_OOT_MARKET_GUARD_HOUSE,
    /* 0x4E */ SCENE_OOT_POTION_SHOP_GRANNY,
    /* 0x4F */ SCENE_OOT_GANON_BOSS,
    /* 0x50 */ SCENE_OOT_HOUSE_OF_SKULLTULA,
    /* 0x51 */ SCENE_OOT_HYRULE_FIELD,
    /* 0x52 */ SCENE_OOT_KAKARIKO_VILLAGE,
    /* 0x53 */ SCENE_OOT_GRAVEYARD,
    /* 0x54 */ SCENE_OOT_ZORAS_RIVER,
    /* 0x55 */ SCENE_OOT_KOKIRI_FOREST,
    /* 0x56 */ SCENE_OOT_SACRED_FOREST_MEADOW,
    /* 0x57 */ SCENE_OOT_LAKE_HYLIA,
    /* 0x58 */ SCENE_OOT_ZORAS_DOMAIN,
    /* 0x59 */ SCENE_OOT_ZORAS_FOUNTAIN,
    /* 0x5A */ SCENE_OOT_GERUDO_VALLEY,
    /* 0x5B */ SCENE_OOT_LOST_WOODS,
    /* 0x5C */ SCENE_OOT_DESERT_COLOSSUS,
    /* 0x5D */ SCENE_OOT_GERUDOS_FORTRESS,
    /* 0x5E */ SCENE_OOT_HAUNTED_WASTELAND,
    /* 0x5F */ SCENE_OOT_HYRULE_CASTLE,
    /* 0x60 */ SCENE_OOT_DEATH_MOUNTAIN_TRAIL,
    /* 0x61 */ SCENE_OOT_DEATH_MOUNTAIN_CRATER,
    /* 0x62 */ SCENE_OOT_GORON_CITY,
    /* 0x63 */ SCENE_OOT_LON_LON_RANCH,
    /* 0x64 */ SCENE_OOT_OUTSIDE_GANONS_CASTLE,
    /* 0x65 */ SCENE_OOT_TEST01,
    /* 0x66 */ SCENE_OOT_BESITU,
    /* 0x67 */ SCENE_OOT_DEPTH_TEST,
    /* 0x68 */ SCENE_OOT_SYOTES,
    /* 0x69 */ SCENE_OOT_SYOTES2,
    /* 0x6A */ SCENE_OOT_SUTARU,
    /* 0x6B */ SCENE_OOT_HAIRAL_NIWA2,
    /* 0x6C */ SCENE_OOT_SASATEST,
    /* 0x6D */ SCENE_OOT_TESTROOM,
    SCENE_OOT_MAX
} SceneIdOot;

// A reference to a scene from either game. `index` is MM's native `SceneId` when
// origin == SCENE_ORIGIN_MM, or `SceneIdOot` (this file) when origin == SCENE_ORIGIN_OOT.
// Use this instead of a raw scene id int anywhere both games' scenes need to be
// referred to interchangeably (Map/Quest dual pages, world-swap logic).
typedef struct CompatSceneRef {
    /* 0x0 */ SceneOrigin origin;
    /* 0x4 */ s16 index;
} CompatSceneRef;

static inline CompatSceneRef Scene_RefMm(s16 mmSceneId) {
    CompatSceneRef ref;
    ref.origin = SCENE_ORIGIN_MM;
    ref.index = mmSceneId;
    return ref;
}

static inline CompatSceneRef Scene_RefOot(s16 ootSceneId) {
    CompatSceneRef ref;
    ref.origin = SCENE_ORIGIN_OOT;
    ref.index = ootSceneId;
    return ref;
}

static inline bool Scene_RefIsOot(CompatSceneRef ref) {
    return ref.origin == SCENE_ORIGIN_OOT;
}

// Returns the human-readable name for either a MM scene (delegates to gSceneTable via
// the existing 2S2H "Human readable name" column) or an OOT scene (this file's
// generated sSceneOotHumanNames table). Implemented in z_scene_origin.c.
const char* Scene_GetHumanName(CompatSceneRef ref);

// Returns which world (MM or OOT) the player is currently in, backed by the persisted
// `ShipSaveInfo.so2h.currentWorld` save field (z64save.h) so it survives save/load.
// Defaults to SCENE_ORIGIN_MM until the Song of Time world-swap feature (separate,
// not-yet-implemented patch per the locked pause-menu/world-swap design) writes to it.
SceneOrigin Scene_GetCurrentOrigin(PlayState* play);
void Scene_SetCurrentOrigin(PlayState* play, SceneOrigin origin);

#endif // Z_SCENE_ORIGIN_H
