#ifndef SO2H_UI_SHEETS_ASSETS_H
#define SO2H_UI_SHEETS_ASSETS_H

// GENERATED by tools/so2h_gen_sheets.py from
// mm/assets/custom/textures/so2h_menu/sheets.json - do not edit by hand.

#define dgSo2hSheetFrameFilled "__OTR__textures/so2h_menu/gSo2hSheetFrameFilled"
static const ALIGN_ASSET(2) char gSo2hSheetFrameFilledTex[] = dgSo2hSheetFrameFilled;

#define dgSo2hSheetFrameEmpty "__OTR__textures/so2h_menu/gSo2hSheetFrameEmpty"
static const ALIGN_ASSET(2) char gSo2hSheetFrameEmptyTex[] = dgSo2hSheetFrameEmpty;

#define dgSo2hSheetFrameRaising "__OTR__textures/so2h_menu/gSo2hSheetFrameRaising"
static const ALIGN_ASSET(2) char gSo2hSheetFrameRaisingTex[] = dgSo2hSheetFrameRaising;

#define dgSo2hSheetFrameBacked "__OTR__textures/so2h_menu/gSo2hSheetFrameBacked"
static const ALIGN_ASSET(2) char gSo2hSheetFrameBackedTex[] = dgSo2hSheetFrameBacked;

#define dgSo2hSheetFramePopup "__OTR__textures/so2h_menu/gSo2hSheetFramePopup"
static const ALIGN_ASSET(2) char gSo2hSheetFramePopupTex[] = dgSo2hSheetFramePopup;

#define dgSo2hSheetFrameGlass "__OTR__textures/so2h_menu/gSo2hSheetFrameGlass"
static const ALIGN_ASSET(2) char gSo2hSheetFrameGlassTex[] = dgSo2hSheetFrameGlass;

#define dgSo2hSheetSongBackdrop "__OTR__textures/so2h_menu/gSo2hSheetSongBackdrop"
static const ALIGN_ASSET(2) char gSo2hSheetSongBackdropTex[] = dgSo2hSheetSongBackdrop;

#define dgSo2hSheetCornerFix "__OTR__textures/so2h_menu/gSo2hSheetCornerFix"
static const ALIGN_ASSET(2) char gSo2hSheetCornerFixTex[] = dgSo2hSheetCornerFix;

#define dgSo2hSheetBigButton "__OTR__textures/so2h_menu/gSo2hSheetBigButton"
static const ALIGN_ASSET(2) char gSo2hSheetBigButtonTex[] = dgSo2hSheetBigButton;

#define dgSo2hSheetContentBox "__OTR__textures/so2h_menu/gSo2hSheetContentBox"
static const ALIGN_ASSET(2) char gSo2hSheetContentBoxTex[] = dgSo2hSheetContentBox;

#define dgSo2hSheetMiniButton "__OTR__textures/so2h_menu/gSo2hSheetMiniButton"
static const ALIGN_ASSET(2) char gSo2hSheetMiniButtonTex[] = dgSo2hSheetMiniButton;

#define dgSo2hSheetItems "__OTR__textures/so2h_menu/gSo2hSheetItems"
static const ALIGN_ASSET(2) char gSo2hSheetItemsTex[] = dgSo2hSheetItems;

#define dgSo2hSheetSlab9 "__OTR__textures/so2h_menu/gSo2hSheetSlab9"
static const ALIGN_ASSET(2) char gSo2hSheetSlab9Tex[] = dgSo2hSheetSlab9;

#define dgSo2hSheetSlotEmpty "__OTR__textures/so2h_menu/gSo2hSheetSlotEmpty"
static const ALIGN_ASSET(2) char gSo2hSheetSlotEmptyTex[] = dgSo2hSheetSlotEmpty;

#define dgSo2hSheetSlotItem "__OTR__textures/so2h_menu/gSo2hSheetSlotItem"
static const ALIGN_ASSET(2) char gSo2hSheetSlotItemTex[] = dgSo2hSheetSlotItem;

#define dgSo2hSheetSlotThin "__OTR__textures/so2h_menu/gSo2hSheetSlotThin"
static const ALIGN_ASSET(2) char gSo2hSheetSlotThinTex[] = dgSo2hSheetSlotThin;

#define dgSo2hSheetItemBox "__OTR__textures/so2h_menu/gSo2hSheetItemBox"
static const ALIGN_ASSET(2) char gSo2hSheetItemBoxTex[] = dgSo2hSheetItemBox;

#endif
