#ifndef SO2H_UI_SHEETS_ASSETS_H
#define SO2H_UI_SHEETS_ASSETS_H

// GENERATED by tools/so2h_gen_sheets.py from
// mm/assets/custom/textures/so2h_menu/sheets.json - do not edit by hand.

#define dgSo2hSheetFrameFilled "__OTR__textures/so2h_menu/gSo2hSheetFrameFilled"
static const ALIGN_ASSET(2) char gSo2hSheetFrameFilledTex[] = dgSo2hSheetFrameFilled;

#define dgSo2hSheetFrameEmpty "__OTR__textures/so2h_menu/gSo2hSheetFrameEmpty"
static const ALIGN_ASSET(2) char gSo2hSheetFrameEmptyTex[] = dgSo2hSheetFrameEmpty;

#define dgSo2hSheetFrameRaising "__OTR__textures/so2h_menu/gSo2hSheetFrameRaising"
static const ALIGN_ASSET(2) char gSo2hSheetFrameRaisingTex[] = dgSo2hSheetFrameRaising;

#define dgSo2hSheetFrameBacked "__OTR__textures/so2h_menu/gSo2hSheetFrameBacked"
static const ALIGN_ASSET(2) char gSo2hSheetFrameBackedTex[] = dgSo2hSheetFrameBacked;

#define dgSo2hSheetFramePopup "__OTR__textures/so2h_menu/gSo2hSheetFramePopup"
static const ALIGN_ASSET(2) char gSo2hSheetFramePopupTex[] = dgSo2hSheetFramePopup;

#define dgSo2hSheetSongBackdrop "__OTR__textures/so2h_menu/gSo2hSheetSongBackdrop"
static const ALIGN_ASSET(2) char gSo2hSheetSongBackdropTex[] = dgSo2hSheetSongBackdrop;

#define dgSo2hSheetCornerFix "__OTR__textures/so2h_menu/gSo2hSheetCornerFix"
static const ALIGN_ASSET(2) char gSo2hSheetCornerFixTex[] = dgSo2hSheetCornerFix;

#define dgSo2hSheetBigButton "__OTR__textures/so2h_menu/gSo2hSheetBigButton"
static const ALIGN_ASSET(2) char gSo2hSheetBigButtonTex[] = dgSo2hSheetBigButton;

#define dgSo2hSheetContentBox "__OTR__textures/so2h_menu/gSo2hSheetContentBox"
static const ALIGN_ASSET(2) char gSo2hSheetContentBoxTex[] = dgSo2hSheetContentBox;

#define dgSo2hSheetMiniButton "__OTR__textures/so2h_menu/gSo2hSheetMiniButton"
static const ALIGN_ASSET(2) char gSo2hSheetMiniButtonTex[] = dgSo2hSheetMiniButton;

#define dgSo2hSheetItems "__OTR__textures/so2h_menu/gSo2hSheetItems"
static const ALIGN_ASSET(2) char gSo2hSheetItemsTex[] = dgSo2hSheetItems;

#endif
